# Generated by Django 6.0.5 on 2026-05-16 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fcmdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FCMDevice',
        ),
    ]
