workflows:
  ios_only:
    name: Build iOS Only
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Flutter dependencies
        script: |
          cd mobile
          flutter pub get
          cd ..
      - name: Update iOS minimum version
        script: |
          cd mobile/ios
          # Cập nhật deployment target lên 15.0
          sed -i '' "s/platform :ios, '13.0'/platform :ios, '15.0'/g" Podfile
          pod install
          cd ../..
      - name: Build iOS
        script: |
          cd mobile
          flutter build ios --release --no-codesign --ios-minimum-os-version=15.0
          cd ..
    artifacts:
      - mobile/build/ios/iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - vanhieu25122006@gmail.com