# Generated by Django 6.0.5 on 2026-05-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0003_alter_activity_activity_type_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='level',
            field=models.CharField(choices=[('push', 'Push notification'), ('in_app', 'Thông báo trong app')], default='in_app', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('group_created', 'Tạo nhóm'), ('expense_created', 'Thêm khoản chi'), ('expense_updated', 'Sửa khoản chi'), ('expense_deleted', 'Xóa khoản chi'), ('member_joined', 'Thêm thành viên'), ('payment_created', 'Thanh toán')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('added_to_group', 'Được thêm vào nhóm'), ('member_added_to_group', 'Thành viên mới'), ('debt_created', 'Phát sinh công nợ'), ('expense_updated', 'Khoản chi được cập nhật'), ('expense_deleted', 'Khoản chi bị xóa'), ('debt_reminder_received', 'Nhận nhắc nợ'), ('debt_reminder_sent', 'Đã nhắc nợ'), ('payment_received', 'Nhận thanh toán'), ('payment_sent', 'Đã thanh toán'), ('payment_confirmed', 'Xác nhận thanh toán')], max_length=60),
        ),
    ]
