# Generated by Django 6.0.5 on 2026-05-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0004_notification_level_alter_activity_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('expense_created', 'Thêm khoản chi'), ('expense_updated', 'Sửa khoản chi'), ('expense_deleted', 'Xóa khoản chi'), ('member_joined', 'Thêm thành viên')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
