# Generated by Django 6.0.5 on 2026-05-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0005_alter_activity_activity_type_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='invite_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('expense_created', 'Thêm khoản chi'), ('expense_updated', 'Sửa khoản chi'), ('expense_deleted', 'Xóa khoản chi'), ('member_joined', 'Thành viên tham gia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Chủ nhóm'), ('member', 'Thành viên')], default='member', max_length=20),
        ),
    ]
