# Generated by Django 6.0.5 on 2026-05-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0006_household_invite_code_household_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='invite_code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
