// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN97R3FCEVk-fwQZCrblQZblCqP8IPDb0',
    appId: '1:128851263812:web:555d035a90a8c261439711',
    messagingSenderId: '128851263812',
    projectId: 'test-firebase-6a183',
    authDomain: 'test-firebase-6a183.firebaseapp.com',
    storageBucket: 'test-firebase-6a183.firebasestorage.app',
    measurementId: 'G-J6835NSE47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkkHl-Tfrm4sTXUGMoh-bRTVfcTbwc1Ys',
    appId: '1:128851263812:android:99c8a3b857e61aae439711',
    messagingSenderId: '128851263812',
    projectId: 'test-firebase-6a183',
    storageBucket: 'test-firebase-6a183.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYpLtQNvS8jFTxiIBFZ5HAx7ixJPQRGmc',
    appId: '1:128851263812:ios:ff98a7bbc8e7cb3a439711',
    messagingSenderId: '128851263812',
    projectId: 'test-firebase-6a183',
    storageBucket: 'test-firebase-6a183.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYpLtQNvS8jFTxiIBFZ5HAx7ixJPQRGmc',
    appId: '1:128851263812:ios:ff98a7bbc8e7cb3a439711',
    messagingSenderId: '128851263812',
    projectId: 'test-firebase-6a183',
    storageBucket: 'test-firebase-6a183.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN97R3FCEVk-fwQZCrblQZblCqP8IPDb0',
    appId: '1:128851263812:web:94aba972fda8e02e439711',
    messagingSenderId: '128851263812',
    projectId: 'test-firebase-6a183',
    authDomain: 'test-firebase-6a183.firebaseapp.com',
    storageBucket: 'test-firebase-6a183.firebasestorage.app',
    measurementId: 'G-JM34N3H760',
  );
}
